### ISSUE TITLE
resolution of training and evalutaion. 

### ISSUE THREAD

**Issue by Caoang327** [facebookresearch/Neural_3D_Video#11]
Hi. 

I am curious about the exact image size/ resolution for both training and testing. The paper mentioned that videos are evaluated at 1K resolution but don't tell the training resolution.  Thanks so much!

**Comment by zhaoyang-lv** [comment]
The results shown in the paper are trained at the same resolution being evaluated, also at 1K. Later we also trained the model at full resolution with slightly longer time (cannot precisely measure, but roughly twice the duration) and the visual results will look slightly better rendered at full resolution. In the end we stick to the original 1K evaluation setting because that saves the computation in evaluation for all experiments and ablation study.
